In [ ]:
import os
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
DATA_DIR = r"H:\Downloads\Move to Mars\raw_data"

In [23]:
def check_data_quality(df, name):
    print(f"\n==================================================")
    print(f" ANALYSE DE LA TABLE : {name}")
    print(f"==================================================")
    print(f"• Dimensions : {df.shape[0]} lignes, {df.shape[1]} colonnes")
    
    # 1. Doublons stricts
    dup_count = df.duplicated().sum()
    print(f"• Doublons stricts : {dup_count} ({dup_count/len(df)*100:.2f}%)")
    
    # 2. Valeurs manquantes
    missing = df.isnull().sum()
    missing_cols = missing[missing > 0]
    if not missing_cols.empty:
        print("• Valeurs manquantes :")
        for col, count in missing_cols.items():
            print(f"  - {col}: {count} NULL ({count/len(df)*100:.2f}%)")
    else:
        print("• Valeurs manquantes : Aucune (100% complet)")
        
    # 3. Métadonnées des colonnes (Noms, Types & Exemples)
    print("\n Détail des colonnes et types de données :")
    col_summary = pd.DataFrame({
        'Type': df.dtypes.astype(str),
        'Non-Null': df.notnull().sum(),
        'Valeurs Uniques': df.nunique(),
        'Exemple': [df[col].iloc[0] if len(df) > 0 else None for col in df.columns]
    })
    display(col_summary)
    
    # 4. Aperçu des 3 premières lignes (Affiche le tableau HTML propre)
    print("\n Aperçu des 3 premières lignes :")
    display(df.head(3))

In [24]:
# ----------------------------------------------------
# 1. TABLE : COLON
# ----------------------------------------------------
df_colon = pd.read_csv(os.path.join(DATA_DIR, "COLON.csv"))
check_data_quality(df_colon, "COLON")
# Vérification des Unicités / Clé Primaire
print(" -> Unicité id_colon :", df_colon['id_colon'].is_unique)

==================================================
 ANALYSE DE LA TABLE : COLON
==================================================
• Dimensions : 255 lignes, 11 colonnes
• Doublons stricts : 4 (1.57%)
• Valeurs manquantes :
  - age: 1 NULL (0.39%)

 Détail des colonnes et types de données :

                         Type  Non-Null  Valeurs Uniques      Exemple
id_colon                  str       255              250     COL-0001
nom                       str       255               20       Benali
prenom                    str       255               33         Hugo
sexe                      str       255                2            H
age                   float64       254               45         42.0
id_categorie_metier       str       255               13       CAT-03
profession                str       255               13   Biologiste
groupe_sanguin            str       255                8          AB+
statut_operationnel       str       255                4        ACTIF
sol_arrivee             int64       255               74            4
id_module_habitation      str       255               19  MOD-HAB-007

 Aperçu des 3 premières lignes :

,id_colon,nom,prenom,sexe,age,id_categorie_metier,profession,groupe_sanguin,statut_operationnel,sol_arrivee,id_module_habitation
0,COL-0001,Benali,Hugo,H,42.0,CAT-03,Biologiste,AB+,ACTIF,4,MOD-HAB-007
1,COL-0002,Rossi,Nina,F,36.0,CAT-02,Infirmier,O+,ACTIF,60,MOD-HAB-003
2,COL-0003,Durand,Rayan,H,43.0,CAT-01,Médecin,A+,CONVALESCENCE,76,MOD-HAB-010

 -> Unicité id_colon : False

In [25]:
# TABLE : CONSTANTE_VITALE (Table de faits)
df_constantes = pd.read_csv(os.path.join(DATA_DIR, "CONSTANTE_VITALE.csv"))
check_data_quality(df_constantes, "CONSTANTE_VITALE")

# Vérification des bornes physiologiques (Outliers)
print("\n• Outliers Physiologiques dans CONSTANTE_VITALE :")
for col, (vmin, vmax) in {'spo2': (70, 100), 'bpm': (40, 180), 'temperature': (35, 42)}.items():
    if col in df_constantes.columns:
        outliers = df_constantes[(df_constantes[col] < vmin) | (df_constantes[col] > vmax)]
        print(f"  - Anomalies [{col}] (hors {vmin}-{vmax}) : {len(outliers)} lignes")

==================================================
 ANALYSE DE LA TABLE : CONSTANTE_VITALE
==================================================
• Dimensions : 216031 lignes, 12 colonnes
• Doublons stricts : 0 (0.00%)
• Valeurs manquantes :
  - timestamp_mesure: 88 NULL (0.04%)
  - score_stress: 418 NULL (0.19%)
  - score_fatigue: 302 NULL (0.14%)
  - qualite_signal: 251 NULL (0.12%)

 Détail des colonnes et types de données :

,Type,Non-Null,Valeurs Uniques,Exemple
id_constante,str,216031,216031,CV-000000001
id_colon,str,216031,484,COL-0113
id_temps,str,216031,8800,T-006383
timestamp_mesure,str,215943,11414,2075-03-08 11:30:00
sol_mars,int64,216031,93,67
frequence_cardiaque_bpm,int64,216031,47,86
saturation_o2_pct,float64,216031,84,97.9
temperature_corporelle_c,float64,216031,21,36.6
score_stress,str,215613,2343,59.1
score_fatigue,str,215729,2076,18.7
qualite_signal,str,215780,3,OK
id_scenario,str,216031,4,SCEN-001

 Aperçu des 3 premières lignes :

,id_constante,id_colon,id_temps,timestamp_mesure,sol_mars,frequence_cardiaque_bpm,saturation_o2_pct,temperature_corporelle_c,score_stress,score_fatigue,qualite_signal,id_scenario
0,CV-000000001,COL-0113,T-006383,2075-03-08 11:30:00,67,86,97.9,36.6,59.1,18.7,OK,SCEN-001
1,CV-000000002,COL-0211,T-004064,2075-02-12 07:45:00,43,113,90.1,38.6,52.8,23.8,OK,SCEN-001
2,CV-000000003,COL-0061,T-002195,2075-01-23 20:30:00,23,67,98.6,36.7,62.6,27.5,OK,SCEN-001

• Outliers Physiologiques dans CONSTANTE_VITALE :

In [26]:
# TABLE : CATEGORIE_METIER
df_metier = pd.read_csv(os.path.join(DATA_DIR, "CATEGORIE_METIER.csv"))
check_data_quality(df_metier, "CATEGORIE_METIER")

==================================================
 ANALYSE DE LA TABLE : CATEGORIE_METIER
==================================================
• Dimensions : 13 lignes, 4 colonnes
• Doublons stricts : 0 (0.00%)
• Valeurs manquantes : Aucune (100% complet)

 Détail des colonnes et types de données :

                      Type  Non-Null  Valeurs Uniques  Exemple
id_categorie_metier    str        13               13   CAT-01
libelle_metier         str        13               13  Médecin
famille_metier         str        13                9    Santé
effectif_cible       int64        13                9        5

 Aperçu des 3 premières lignes :

  id_categorie_metier libelle_metier famille_metier  effectif_cible
0              CAT-01        Médecin          Santé               5
1              CAT-02      Infirmier          Santé              10
2              CAT-03     Biologiste          Santé              12

In [27]:
# TABLE : MODULE (HABITATS)

df_module = pd.read_csv(os.path.join(DATA_DIR, "MODULE.csv"))
check_data_quality(df_module, "MODULE")

==================================================
 ANALYSE DE LA TABLE : MODULE
==================================================
• Dimensions : 39 lignes, 7 colonnes
• Doublons stricts : 0 (0.00%)
• Valeurs manquantes : Aucune (100% complet)

 Détail des colonnes et types de données :

                Type  Non-Null  Valeurs Uniques       Exemple
id_module        str        39               39   MOD-HAB-001
type_module      str        39                9       Habitat
nom_module       str        39               39     Habitat 1
capacite       int64        39               23            28
statut_module    str        39                7  OPERATIONNEL
zone_colonie     str        39                6           Est
niveau_risque    str        39                9        FAIBLE

 Aperçu des 3 premières lignes :

,id_module,type_module,nom_module,capacite,statut_module,zone_colonie,niveau_risque
0,MOD-HAB-001,Habitat,Habitat 1,28,OPERATIONNEL,Est,FAIBLE
1,MOD-HAB-002,Habitat,Habitat 2,15,operationnel,Nord,ELEVE
2,MOD-HAB-003,Habitat,Habitat 3,25,OP,Inconnue,FAIBLE

In [28]:
# TABLE : DIM_TEMPS_MARS

df_temps = pd.read_csv(os.path.join(DATA_DIR, "DIM_TEMPS_MARS.csv"))
check_data_quality(df_temps, "DIM_TEMPS_MARS")

==================================================
 ANALYSE DE LA TABLE : DIM_TEMPS_MARS
==================================================
• Dimensions : 64224 lignes, 13 colonnes
• Doublons stricts : 0 (0.00%)
• Valeurs manquantes :
  - sol_dans_annee: 59 NULL (0.09%)
  - sol_dans_mois: 61 NULL (0.09%)

 Détail des colonnes et types de données :

                      Type  Non-Null  Valeurs Uniques              Exemple
id_temps               str     64224            64224             T-000001
datetime_terre         str     64224            64224  2075-01-01 00:00:00
date_terre             str     64224              841           2075-01-01
sol_mars             int64     64224              669                    1
sol_dans_annee     float64     64165              669                  1.0
nom_mois_mars          str     64224               24              Mois 01
sol_dans_mois      float64     64163               30                  1.0
semaine_mars         int64     64224               96                    1
jour_semaine_mars      str     64224                7                Sol 1
saison_mars            str     64224                4            Printemps
trimestre_mars       int64     64224                4                    1
periode_sol            str     64224                4                 Nuit
cycle_activite         str     64224                3                Repos

 Aperçu des 3 premières lignes :

,id_temps,datetime_terre,date_terre,sol_mars,sol_dans_annee,nom_mois_mars,sol_dans_mois,semaine_mars,jour_semaine_mars,saison_mars,trimestre_mars,periode_sol,cycle_activite
0,T-000001,2075-01-01 00:00:00,2075-01-01,1,1.0,Mois 01,1.0,1,Sol 1,Printemps,1,Nuit,Repos
1,T-000002,2075-01-01 00:15:00,2075-01-01,1,1.0,Mois 01,1.0,1,Sol 1,Printemps,1,Nuit,Repos
2,T-000003,2075-01-01 00:30:00,2075-01-01,1,1.0,Mois 01,1.0,1,Sol 1,Printemps,1,Nuit,Repos

In [29]:
# TABLE : SCENARIO

df_scenario = pd.read_csv(os.path.join(DATA_DIR, "SCENARIO.csv"))
check_data_quality(df_scenario, "SCENARIO")

==================================================
 ANALYSE DE LA TABLE : SCENARIO
==================================================
• Dimensions : 4 lignes, 4 colonnes
• Doublons stricts : 0 (0.00%)
• Valeurs manquantes : Aucune (100% complet)

 Détail des colonnes et types de données :

               Type  Non-Null  Valeurs Uniques            Exemple
id_scenario     str         4                4           SCEN-001
nom_scenario    str         4                4  Nominal / Routine
type_evenement  str         4                3       Opérationnel
niveau_gravite  str         4                4             FAIBLE

 Aperçu des 3 premières lignes :

  id_scenario                nom_scenario   type_evenement niveau_gravite
0    SCEN-001           Nominal / Routine     Opérationnel         FAIBLE
1    SCEN-002  Tempête de poussière Alpha  Environnemental          ELEVÉ
2    SCEN-003    Chute de pression Module        Technique       CRITIQUE